### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by davechurchill** [cflewis/Infinite-Mario-Bros#1]
Is this library complete? Also, do you have any instructions on how to run it, now that the official infinite mario site has been taken down?

**Comment by cflewis** [comment]
It was a full fork, so it is complete in that sense.

My Maven is rusty, but this worked:

```
git clone https://github.com/cflewis/Infinite-Mario-Bros.git
cd Infinite-Mario-Bros
mvn package
java -jar target/Mario-1.0-jar-with-dependencies.jar
```

It seems to execute OK, but display rendering on my Debian machine was broken. YMMV. HTH!
